language: python
python:
  - "2.7"
install:
  - sudo pip install -r test_requirements.txt --use-mirrors
before_script:
  - pep8 *.py
  - pylint --rcfile=pylint.conf *.py
script:
  - ./docker_dns_test.py